#!/bin/bash 
#
# ##########################################################################
# +----------------------------------------------------------------------+ #
# |                 SRE ROOT SETUP                                       | #
# +----------------------------------------------------------------------+ #
# |                                                                      | #
# | Name          : main.sh                                              | #
# | Function      : startup sre tools install                            | #
# | Version       : 1.0                                                  | #
# | Author        : Jorge Gabriel (SRE)                                  | #
# | Email         : jorgegabriel.ti@gmail.com                            | #
# +----------------------------------------------------------------------+ #
# ##########################################################################
#
# Description:
#
# Algortimo do script :
#  Install SRE tools for start work.
# --------------------------------------------------------------------------## Alias eXpands
shopt -s expand_aliases

### Workdir
WORK_DIR="${PWD}"

### Import functions
for FUNCTION in $(grep -F 'Test: [OK]' -l -r ${WORK_DIR}/src/function/); do
  sed -i 's/\r$//' ${FUNCTION}
  source ${FUNCTION}
done

### System configurations
distro_detect && \
  update_system

### Packages installations
packages_install

### Python install
python_install

## TODO: user firebug para sites cujo o download 
## de artefatos não seja tão simples. Usar curl em seguida.
#

#### Containers tools
## Docker
docker_install

#### IaC Tools
## Ansible
ansible_install

## Vagrant
vagrant_install 

## Terraform
terraform_install 

#### Cloud Tools 
## aws-cli
awscli_install

## gcloud
# Doc: https://cloud.google.com/sdk/docs/quickstart-linux
gcloud_install

## Kubernetes
## kind
kind_install

## istio
istio_install

## Kubectl
kubectl_install

## Check
check_packages_install