#!/bin/bash 
#
# ##########################################################################
# +----------------------------------------------------------------------+ #
# |                 Backup Shell                                         | #
# +----------------------------------------------------------------------+ #
# |                                                                      | #
# | Name          : main.sh                                              | #
# | Function      : startup sre tools install                            | #
# | Version       : 1.0                                                  | #
# | Author        : Jorge Gabriel (SRE)                                  | #
# | Email         : jorgegabriel.ti@gmail.com                            | #
# +----------------------------------------------------------------------+ #
# ##########################################################################
#
# Description:
#
# Algortimo do script :
#  Install SRE tools for start work.
#

### Alias eXpands
shopt -s expand_aliases

### Workdir
WORK_DIR="${PWD}"

### Import functions
for FUNCTION in $(grep -F 'Test: [OK]' -l -r ${WORK_DIR}/src/function/); do
    sed -i 's/\r$//' ${FUNCTION}
    source ${FUNCTION}
done

### System configurations
distro_detect && \
  update_system

### Packages installations
packages_install

### Python install
python_install

## TODO: user firebug para sites cujo o download 
## de artefatos não seja tão simples. Usar curl em seguida.
#

#### Containers tools
## Docker
docker_install

## Kubernetes
## kind
kind_install

## Kubectl
kubectl_install

#
#
## istio
#curl -L https://istio.io/downloadIstio | sh -
#cd istio-*
#
#istioctl install \ 
#  --set profile=default -y \
#  --set meshConfig.accessLogFile=/dev/stdout
#
#### IaC Tools
## Ansible
ansible_install

## Vagrant
vagrant_install 

## Terraform
terraform_install 

#curl -fsSL https://apt.releases.hashicorp.com/gpg \
#  | sudo apt-key add -
#sudo apt-add-repository \
#  "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
#sudo apt-get update -y \
#  && sudo apt-get install -y \
#  terraform
#
#terraform -v
#
#### Cloud Tools 
## aws-cli
#curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \ 
#  -o "awscliv2.zip"
#unzip awscliv2.zip
#sudo ./aws/install
#
## gcloud
#echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
#  | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
#sudo apt-get install apt-transport-https ca-certificates gnupg
#curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
#  | sudo apt-key \
#    --keyring /usr/share/keyrings/cloud.google.gpg add -
#sudo apt-get update && sudo apt-get install google-cloud-sdk